* Add gettext support (i18n)  * Add language catalogs (pt pt_PT)

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 ## Process this file with automake to produce Makefile.in
-## Created by Anjuta
 
 SUBDIRS = src po
+
 
 guvcviewdocdir = ${prefix}/doc/guvcview
 guvcviewdoc_DATA = \
@@ -12,7 +12,9 @@ guvcviewdoc_DATA = \
 	INSTALL\
 	NEWS
 
-EXTRA_DIST = $(guvcviewdoc_DATA)
+ACLOCAL_AMFLAGS = -I m4
+
+EXTRA_DIST = config.rpath src $(guvcviewdoc_DATA)
 
 # Copy all the spec files. Of cource, only one is actually used.
 dist-hook:
@@ -21,4 +23,27 @@ dist-hook:
 			cp -p $$specfile $(distdir); \
 		fi \
 	done
+
+check-gettext:
+	@if test x$(USE_NLS) != "xyes" ; then echo "Missing gettext. Rerun configure and check for" \
+	"'checking whether to use NLS... yes'!" ; exit 1 ; fi
+
+update-po: check-gettext
+	@find $(srcdir)/src/ -name "*.cpp" -print | sort > $(srcdir)/po/POTFILES.in.2 ; \
+	if diff $(srcdir)/po/POTFILES.in $(srcdir)/po/POTFILES.in.2 >/dev/null 2>&1 ; then \
+		rm -f $(srcdir)/po/POTFILES.in.2 ; \
+	else \
+		mv $(srcdir)/po/POTFILES.in.2 $(srcdir)/po/POTFILES.in ; \
+	fi
+	cd po && $(MAKE) $(AM_MAKEFLAGS) update-po
+
+update-gmo: check-gettext
+	cd po && $(MAKE) $(AM_MAKEFLAGS) update-gmo
+
+force-update-gmo: check-gettext
+	touch po/*.po
+	cd po && $(MAKE) $(AM_MAKEFLAGS) update-gmo
+
+
+.PHONY: check-gettext update-po update-gmo force-update-gmo
 
